### ISSUE TITLE
why add the plugin to config file when it works without it anyway?

### ISSUE THREAD

**Issue by kurtgn** [mkurnikov/djangorestframework-stubs#16]
Hi,
first off - thanks for the effort of maintaining this!

Now, the question:

Consider this example
```
from rest_framework.response import Response
from rest_framework.views import APIView


class PushStateToChatView(APIView):
    renderer_classes = ['a', 'b']
    def post(self) -> Response:
        return Response({'status': 'ok'})

```

this produces mypy errors:

```
mypy api/partners/views.py
api/partners/views.py:9: error: List item 0 has incompatible type "str"; expected "Type[BaseRenderer]"
api/partners/views.py:9: error: List item 1 has incompatible type "str"; expected "Type[BaseRenderer]"
```

and - watch this: **it works even without adding the `mypy_drf_plugin.main` to `mypy.ini`.**

So, can you please show an example of something that works only if the plugin is added to `mypy.ini` - and does not work without it?

Cheers!

**Comment by aleksanb** [comment]
I usually look at the tests in https://github.com/mkurnikov/djangorestframework-stubs/tree/master/test-data/typecheck, they showcase type inference that's only possible due to the plugin itself.

For instance, in https://github.com/mkurnikov/djangorestframework-stubs/blob/master/test-data/typecheck/model_instances.test#L37 we see that the plugin returns the correct model type from Serializer.create(), behavior that's not possible if you only have stubs.

**Comment by mkurnikov** [comment]
I assume it's resolved, not all behaviours could be expressed with type hints, sometimes plugin is required.
